### ISSUE TITLE
Does not support Chinese

### ISSUE THREAD

**Issue by TimChen44** [ostreifel/duplicate-bug#1]
olivernn/lunr.js not support Chinese，Whether you can use linfuyan/lunr.js ？

**Comment by ostreifel** [comment]
The only change I can find in linfuyan's branch is an [update to the readme.md](https://github.com/linfuyan/lunr.js/commits/master).

I looked through the issues in olivernn/lunr.js and found [these](https://github.com/olivernn/lunr.js/issues?utf8=%E2%9C%93&q=chinese).
With [this](https://github.com/olivernn/lunr.js/issues/302) and [this](https://github.com/olivernn/lunr.js/issues/173) specifically mentioning chinese support.

There seems to be a [related project (lunr-languages)](https://github.com/MihaiValentin/lunr-languages) for supporting languages but Chinese is not one of them.

I'll try to add support for MihaiValentin/lunr-languages to broaden support and make it easy to add chinese support once lunr-languages supports it. 
Currently issues [32](https://github.com/MihaiValentin/lunr-languages/issues/32), [19](https://github.com/MihaiValentin/lunr-languages/issues/19), and [17](https://github.com/MihaiValentin/lunr-languages/issues/17) are requesting that support but I don't see anyone actively working on it.

As I do not have any background in the language I'll have to wait for someone else to add support for Mandarin to MihaiValentin/lunr-languages.
