### ISSUE TITLE
Extension causes TFS work item to freeze

### ISSUE THREAD

**Issue by Scott-Emberson** [ostreifel/duplicate-bug#2]
When you start to write the title, the extension then goes to start looking for any related work items but at this point, it freezes the current work item so you are unable to continue entering anymore information e.g. Area Path

**Comment by ostreifel** [comment]
I am unable to repro this on vsts. What are your environment details?
TFS Version
Browser
Extension Version
etc

**Comment by Scott-Emberson** [comment]
@ostreifel As requested:
TFS Version - TFS 2017 Update 3
Browser - Google Chrome 63.0.3239.132 (Official Build) (64-bit)
Extension Version - 1.0.28

**Comment by ostreifel** [comment]
I just setup a vm w/
```
Tfs Version 15.117.27024.0 (tfs 2017 u3 rtm), 
chrome 63.0.3239.132 (Official Build) (64-bit) (cohort: Stable)
Extension 1.0.28
```
with no repo.

Are there any exceptions seen in the browser console (12)? Anything else that might make the installation different from the test environment?

**Comment by Scott-Emberson** [comment]
Hi, we have also the multivalue control installed. (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-extensions-multivalue-control) 
There was no error's seen in the console.
So if I watch the network, I can see it making all the calls to the API what run fine. Then when it's finished getting the results it generates them into the work items, it's at that point it freezes

**Comment by ostreifel** [comment]
Can you email a [network trace](https://www.telerik.com/fiddler/fiddlercap) to ottost@microsoft.com?

**Comment by philmagr** [comment]
I am also experiencing this issue, but in VSTS - though I don't think it's network related, directly. 

It's more likely related to the fact that for a single item it's pulling back ~6+ megabytes worth of bugs. 5 network requests getting back approximately 200 work items each, each request coming back with between 1-3 MB of JSON. The problem likely only happens in environments with very large numbers of work items to search through and match, with large description fields with lots of HTML styling.
